### ISSUE TITLE
Can't run this project. 

### ISSUE THREAD

**Issue by nhatquang0672** [haribo0915/mit-6.824-distributed-systems#1]
Do you use Go version 1.17?
I don't know how to get work with lockd.go, lockc.go ...? This stuff always so can't import.
Can you help me? @haribo0915

**Comment by haribo0915** [comment]
Hi @nhatquang0672, it works well for me with Go 1.17. Since the project layout doesn't go by the rule, I suggest you follow the instructions described in [each lab section](http://nil.csail.mit.edu/6.824/2020/) to run it first. I think files such as lockd.go, lockc.go or diskvd.go are the legacy of previous labs (prior to Spring 2020). They existed when I cloned the initial lab software from "git://g.csail.mit.edu/6.824-golabs-2020", but I actually didn't use them.

**Comment by nhatquang0672** [comment]
Thanks @haribo0915 .
